### ISSUE TITLE
Add RoR sample

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako-samples#6]
Add sample Ruby on Rails project

**Comment by maxirmx** [comment]
ror sample added in  https://github.com/tamatebako/tebako-samples/pull/5

**Comment by ronaldtse** [comment]
@maxirmx thank you! Can you also add a blog post to announce support for rails? Thanks!

**Comment by maxirmx** [comment]
@ronaldtse I wrote a draft: https://github.com/tamatebako/tebako.org/pull/36
